#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${snails.datasource.url}
    username: ${snails.datasource.username}
    password: ${snails.datasource.password}

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:3000
