#第三方登陆配置
social:
  oauth:
    WECHAT_OPEN:
      client-id: wx8a92818c87eb1e11
      client-secret: 2df790171d408b95fced7626c87bc6ad
      redirect-uri: ${social.domain}/oauth/redirect/wechat_open
    QQ:
      client-id: wx8a92818c87eb1e11
      client-secret: 2df790171d408b95fced7626c87bc6ad
      redirect-uri: ${social.domain}/oauth/redirect/qq
